-- ==========================================================
-- Retail Intelligence Platform
-- Table: geolocation
-- Description:
-- Stores geographical reference information.
-- ==========================================================

CREATE TABLE IF NOT EXISTS retail.geolocation (

    geolocation_key BIGSERIAL PRIMARY KEY,

    geolocation_zip_code_prefix VARCHAR(10) NOT NULL,

    geolocation_lat NUMERIC(10,6) NOT NULL,

    geolocation_lng NUMERIC(10,6) NOT NULL,

    geolocation_city VARCHAR(100) NOT NULL,

    geolocation_state CHAR(2) NOT NULL

);

COMMENT ON TABLE retail.geolocation IS
'Stores geographical reference information.';

COMMENT ON COLUMN retail.geolocation.geolocation_key IS
'Surrogate primary key generated by the database.';

COMMENT ON COLUMN retail.geolocation.geolocation_zip_code_prefix IS
'ZIP code prefix.';

COMMENT ON COLUMN retail.geolocation.geolocation_lat IS
'Latitude coordinate.';

COMMENT ON COLUMN retail.geolocation.geolocation_lng IS
'Longitude coordinate.';

COMMENT ON COLUMN retail.geolocation.geolocation_city IS
'City name.';

COMMENT ON COLUMN retail.geolocation.geolocation_state IS
'Brazilian state abbreviation.';