-- ==========================================================
-- Retail Intelligence Platform
-- Table: order_reviews
-- Description:
-- Stores customer reviews for completed orders.
-- ==========================================================

CREATE TABLE IF NOT EXISTS retail.order_reviews (

    review_key BIGSERIAL PRIMARY KEY,

    review_id VARCHAR(50) NOT NULL,

    order_id VARCHAR(50) NOT NULL,

    review_score INTEGER NOT NULL,

    review_comment_title TEXT,

    review_comment_message TEXT,

    review_creation_date TIMESTAMP NOT NULL,

    review_answer_timestamp TIMESTAMP NOT NULL,

    CONSTRAINT fk_order_reviews_order
        FOREIGN KEY (order_id)
        REFERENCES retail.orders(order_id)

);

COMMENT ON TABLE retail.order_reviews IS
'Stores customer reviews for completed orders.';

COMMENT ON COLUMN retail.order_reviews.review_key IS
'Surrogate primary key generated by the database.';

COMMENT ON COLUMN retail.order_reviews.review_id IS
'Original review identifier from the source dataset.';

COMMENT ON COLUMN retail.order_reviews.order_id IS
'References the reviewed order.';

COMMENT ON COLUMN retail.order_reviews.review_score IS
'Customer rating from 1 to 5.';

COMMENT ON COLUMN retail.order_reviews.review_comment_title IS
'Optional review title.';

COMMENT ON COLUMN retail.order_reviews.review_comment_message IS
'Optional review message.';

COMMENT ON COLUMN retail.order_reviews.review_creation_date IS
'Date the review was created.';

COMMENT ON COLUMN retail.order_reviews.review_answer_timestamp IS
'Timestamp when the review was submitted.';