-- ==========================================================
-- Retail Intelligence Platform
-- DDL - Table Creation Order
-- ==========================================================

-- 1. category_translation
-- 2. customers
-- 3. sellers
-- 4. products
-- 5. orders
-- 6. order_items
-- 7. order_payments
-- 8. order_reviews
-- 9. geolocation